### ISSUE TITLE
How can I listen the segment change event

### ISSUE THREAD

**Issue by robert-luoqing** [alex-melnyk/flutter_advanced_segment#10]
Dear, 

I like your segment style. But I can listen the segment change event. I have tried below code, but it is not working
```
    _controller.addListener(() {
      print("selected: ${_controller.value}");
    });
```

**Comment by MobileMon** [comment]
I would like to know how to listen to changes too

in the standard cupertino control there is -     onValueChanged: (int newValue) {

but this method does not exist in flutter advanced segment
