### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by inexuscore** [alex-melnyk/flutter_advanced_segment#4]
Hi Alex,
Thank you very much for putting this repo together!

I was wondering if it's possible to publish an update and make the segments scrollable, horizontally.
Inside the **_buildSegments** method, I can wrap the **Row** widget inside a **ListView** and make it scroll horizontally, but that breaks the animation and it doesn't work as expected.

I'm fairly new to Flutter, if I could do it myself I'd publish a PR.
Thank you.

**Comment by alex-melnyk** [comment]
Sure, do PR and after merge I'll publish updates

**Comment by inexuscore** [comment]
@alex-melnyk Great. I can submit a PR with the Segment control wrapped in a **ListView** widget, scrollable horizontally. But the animation part is in your hands. Thank you.
